---
name: PR Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group: {}
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: pr-validation-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    # NWarila/terraform-framework-template main @ 2026-05-27
    uses: NWarila/terraform-framework-template/.github/workflows/reusable-terraform-validation.yaml@efcf3274d8bc6f4b192be063db8f284db6d9423a
    with:
      # renovate: datasource=github-releases depName=hashicorp/terraform extractVersion=^v(?<version>.*)$
      terraform_version: "1.15.2"
      # renovate: datasource=github-releases depName=terraform-linters/tflint extractVersion=^v(?<version>.*)$
      tflint_version: "0.62.0"
      # renovate: datasource=github-releases depName=terraform-docs/terraform-docs extractVersion=^v(?<version>.*)$
      terraform_docs_version: "0.23.0"
      # renovate: datasource=github-releases depName=open-policy-agent/opa extractVersion=^v(?<version>.*)$
      opa_version: "1.10.0"
      template_ref: efcf3274d8bc6f4b192be063db8f284db6d9423a
      mode: full
