name: Release Please

on:
  push:
    branches:
      - PROD

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest

    steps:
      - name: Run release-please
        uses: googleapis/release-please-action@a02a34c4d625b9a4a6d26de46e8e4ea2b7fec2bc # v4.2.0
        with:
          release-type: simple
          target-branch: PROD
