name: Terraform Validator

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/terraform.yaml
      - terraform/*.tf

permissions:
  contents: read

concurrency:
  group: terraform-${{ github.event.repository.name }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform:
    name: Terraform
    runs-on:
      - self-hosted
      - X64
    timeout-minutes: 120

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Run Linux composite action
        if: ${{ runner.os == 'Linux' }}
        uses: ./.github/actions/terraform-bash

      - name: Run Windows composite action
        if: ${{ runner.os == 'Windows' }}
        uses: ./.github/actions/terraform-powershell
